### ISSUE TITLE
feat: Add Quizzes to all Chapters of the Book

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#729]
As there have been a lot of requests to contribute lately and to avoid people squatting issues without working on them, please ensure that:
- ⚠️ You have read the entire Cairo Book ⚠️ 
- ⚠️ You have read and understood what makes a good quiz ⚠️ 
- ⚠️ You will be available to bring changes post-review ⚠️ 
- The chapter you want to work on is not being worked on (check the list)
- Given the simplicity of the task, if you want to add a quizz, you must open a pull request in the next 2 days - if you're not available, you can always come back a bit later!

Tasklist:

The Cairo Programming Language:
- [x] Chapter 1 #660 
- [x] Chapter 2 #680 
- [x] Chapter 3.1 Array  #744 
- [x] Chapter 3.2 Dict #755 
- [x] Chapter 4.1 Ownership #760 
- [x] Chapter 4.2 References and Snapshot
- [x] Chapter 5.1 Defining/instantiating structs #759 
- [x] Chapter 5.2 Example #782 
- [x] Chapter 5.3 Method syntax #783 
- [x] Chapter 6.1  enum #769 
- [x] Chapter 6.2 match #771 
- [x] Chapter 6.3 if let / while let #792 
- [x] Chapter 7 Managing packages / modules  #791 
- [x]  Chapter 8 - Generic Types and Traits #785 
- [x] Chapter 8.1  Generic Data Types
- [x] Chapter 8.2  Traits in Cairo
- [x] Chapter 9.1 Unrecoverable errors with panic #787 
- [x] Chapter 9.2 Recoverable errors with Result #775 
- [x] Chapter 10.1 How To Write Tests #779 
- [x] Chapter 10.2 Tests Organisation #788 

- [x] Chapter 11.1 Custom Data Structures #797 
- [x] Chapter 11.3 Smart Pointers
- [x] Chapter 11.4 Operators overloading #799 

Add more relevant quiz. Can take inspiration from the Rust book.

## How to write a good quiz

A good quiz realizes the following points:
- Asks about the concepts in the current chapter
- Encourages in-depth reflection on these concepts
- introduces subtleties to ensure that the concepts are correctly understood

### Example 1 - a bad quiz

>  What happens when you run this function?
```rust
fn main() -> u8 {
    let mut arr = ArrayTrait::<u8>::new();
    arr.append(100);
    arr.append(2);
    let x = *arr.at(2);
    println!("The first value is {}", x); 
    x
}
```

The answer here is straightforward: The array contains 2 elements and we try to access the one at index n. 2. It's not valuable from a pedagogic pov, because the answer is not obsfuscated enough for the user to think deeply about it. 

### Example 2 - a good quiz

> Which call to this `find_until` function will cause a runtime panic?
>   "`find_until(array![1, 2, 3].span(), 0, 0);`",
  "`find_until(array![1, 2, 3].span(), 3, 3);`",
  "`find_until(array![1, 2, 3].span(), 1, 4);`",
  "`find_until(array![1, 2, 3].span(), 4, 4);`"

```rust
fn find_until(mut v: Span<u64>, n: u64, til: usize) -> Option<usize> {
    let mut i = 0;
    loop {
        if i == til {
            break Option::None;
        }
        if *v[i] == n {
            break Option::Some(i);
        }
        i += 1;
    }
}
```

This quiz is a good alternative to the first example, because we're asking about questions about a function whose behavior is unknown at compile time. Depending on the input, the answer changes, and the quiz solver will need to think about _why_ this function is not designed properly.

### Example 3 - a useless quiz

Avoid writing quiz that are simply useless: distractors are either too easy or make no sense, the context is not put properly, there's no underlying reflexion

> How can we access array elements without modifying the original array?
> "`array.span();`"
> "`array!`",
"`ArrayTrait::new();`"

### Example 4 - taking things one level further

The book's purpose is to introduce the reader to the main concepts of the Cairo language, and teach how one can uses Cairo to build programs. But its purpose is not to demonstrate how to achieve very specific situations: that exercise is left to the reader. For instance, consider dictionaries and `Felt252Dict`. We know that we can manipulate a non-copyable data structure with `entry` and `finalize`. We learnt how `get` works under the hood and how one can write custom accessors for dicitonary elements. To take it one step further: how can we combine these concepts to unlock new methods of working with dicitionaries ? 

The following example could be adapted to demonstrate how we can mutate arrays inside dictionaries, and that would be the best quiz example possible
-  Requires deep understanding of dicts
- Forces deep thinking about the problem, reusing concepts introduced in the section, but with no straightforward answer
- Comes with a lot of subtleties that can only be understood after playing around with Cairo and getting more familiar with the concepts.

```rust
fn main() {
    let temperatures = array![20, 19, 26];
    let mut pixels: Felt252Dict<Nullable<Array<u8>>> = Default::default();
    pixels.insert(0, NullableTrait::new(temperatures));
    println!("Before insertion: {:?}", get_array_entry(ref pixels, 0));

    append_value(ref pixels, 0, 30);

    println!("After insertion: {:?}", get_array_entry(ref pixels, 0));
}

fn append_value(ref pixels: Felt252Dict<Nullable<Array<u8>>>, index: felt252, value: u8) {
    let (entry, temperatures) = pixels.entry(0);
    let mut unboxed_val = temperatures.deref_or(array![]);
    unboxed_val.append(value);
    pixels = entry.finalize(NullableTrait::new(unboxed_val));
}

fn get_array_entry(ref pixels: Felt252Dict<Nullable<Array<u8>>>, index: felt252) -> Span<u8> {
    let (entry, _temperatures) = pixels.entry(0);
    let mut temperatures = _temperatures.deref_or(array![]);
    let temps = temperatures.span();
    pixels = entry.finalize(NullableTrait::new(temperatures));
    temps
}
```

**Comment by Zeegaths** [comment]
hey @enitrat please assign me this

**Comment by Zeegaths** [comment]
Hello, can I take this?

**Comment by enitrat** [comment]
Hi, you can start a few questions for this page:
https://book.cairo-lang.org/ch03-01-arrays.html

**Comment by Zeegaths** [comment]
okay

**Comment by FriendlyLifeguard** [comment]
Hello, can I take this?

**Comment by TAdev0** [comment]
Sure @FriendlyLifeguard, a few have already been added, you can check which chapter don't have quizz yet!

**Comment by Ayoazeez26** [comment]
@TAdev0 can I add quizzes to chapters that don't have yet?

**Comment by enitrat** [comment]
@Ayoazeez26 any specific chapter you want to start with ?

**Comment by ebukizy1** [comment]
i see this issues is still open can i jump on this and work on it..

**Comment by lindsaymoralesb** [comment]
Hi! @enitrat are there still chapters missing quizzes? If so, I would like to contribute

**Comment by No-bodyq** [comment]
Hey, @enitrat can i join in on this

**Comment by Ayoazeez26** [comment]
@enitrat @TAdev0  I see that chapter 4 does not have any quizzes, I guess I can start with that

**Comment by TAdev0** [comment]
@Ayoazeez26  yes please go ahead!

If anyone else is interested in this issue: 
- Please read all the content of the issue.
- Then, check in the book and in the current PR which chapter don't have quizz yet
- comment on the issue and propose the chapter(s) you'd like to add quiz to

**Comment by No-bodyq** [comment]
I'd like to start with chapter 5

**Comment by enitrat** [comment]
sure, make sure to check the quiz guidelines in the issue description

**Comment by NueloSE** [comment]
@enitrat @TAdev0 can i work on [c10 Testing](https://book.cairo-lang.org/ch10-00-testing-cairo-programs.html)

**Comment by TAdev0** [comment]
hi, sure go ahead @NueloSE !

**Comment by lindsaymoralesb** [comment]
Hi! @TAdev0 @enitrat Can i work on: chapter 3 (just dictionaries is missing quizzes) and chapter 6 ? :)

**Comment by TAdev0** [comment]
@lindsaymoralesb  sure, you can go with 6.1 Enum . dont hesitate to look at quizzes already available for chapter 1, 2 and 3.1

**Comment by TAdev0** [comment]
@NueloSE  go ahead, either 10.1 or 10.2 !

**Comment by addegbenga** [comment]
@TAdev0 can i work on chapter 9

**Comment by TAdev0** [comment]
@addegbenga  hey, sure!

**Comment by CollinsC1O** [comment]
@enitrat Hi can I Work on chapter 8

**Comment by TAdev0** [comment]
hi @CollinsC1O  sure, please go ahead :) feel free to reach out if you need any help

**Comment by Osatuyi** [comment]
Hello @enitrat I will love to work on chapter 7

**Comment by kateberryd** [comment]
Hi @enitrat I would love to work on chapter 11

**Comment by Gift-Naomi** [comment]
Hi @enitrat I will like to work on chapter 5.3

**Comment by No-bodyq** [comment]
Hello @enitrat, @TAdev0 , can i work on chapter 5.2

**Comment by enitrat** [comment]
@EjembiEmmanuel 4.1 is already being worked on

**Comment by EjembiEmmanuel** [comment]
@enitrat sorry it was a mistake I meant 4.2

**Comment by enitrat** [comment]
being worked on as well afaik

**Comment by Ejembiii** [comment]
@enitrat I can work on 8, if nobody is on it

**Comment by Jemiiah** [comment]
can i work on Chapter 8.2 @enitrat

**Comment by Ejembiii** [comment]
Let me work on 9.1 @enitrat

**Comment by leevigh** [comment]
Can I work on chapter 10.1

**Comment by petersdt** [comment]
Hi @enitrat @TAdev0 can i work on [chapter 10.2](https://book.cairo-lang.org/ch10-02-test-organization.html)

**Comment by NueloSE** [comment]
@enitrat @leevigh i have already been assigned ch 10.1 and i made a PR #779 already

**Comment by blessingbytes** [comment]
Hi @enitrat  can i work on chapter 11.1

**Comment by enitrat** [comment]
@blessingbytes you can do 11.4

**Comment by blessingbytes** [comment]
@enitrat i will like to now work on chapter 11.4

**Comment by NueloSE** [comment]
@enitrat can i take on [13.1 General Introduction to Smart Contracts](https://book.cairo-lang.org/ch13-01-general-introduction-to-smart-contracts.html#general-introduction-to-smart-contracts) and [13.2 Anatomy of a Simple Contract](https://book.cairo-lang.org/ch13-02-anatomy-of-a-simple-contract.html#anatomy-of-a-simple-contract)

**Comment by NueloSE** [comment]
@enitrat can i work on [11.3 Smart Pointers](https://book.cairo-lang.org/ch11-03-smart-pointers.html#smart-pointers)

**Comment by enitrat** [comment]
@NueloSE go ahead

**Comment by LamsyA** [comment]
Can I work on 11.5 @enitrat

**Comment by petersdt** [comment]
Hi @enitrat can i assist  with [4.2 Reference and snapshot](https://book.cairo-lang.org/ch04-02-references-and-snapshots.html)

**Comment by No-bodyq** [comment]
Helli @enitrat @TAdev0  can I help out with 4.2

**Comment by enitrat** [comment]
Everything is already being worked on.

**Comment by od-hunter** [comment]
@enitrat @TAdev0 Can i work on chapter 111110.1- how to write tets?
